name       : aa-lsm-hook
version    : 0.1.2
release    : 11
source     :
    - https://github.com/getsolus/aa-lsm-hook/archive/0.1.2.tar.gz : 80620baf1ad819a29eefc437f4f00abe0e352d395b9b5739d60914fd5c075b14
license    : Apache-2.0
component  : system.base
summary    : AppArmor system integration
description: |
    AppArmor system integration
builddeps  :
    - golang
networking : yes
build      : |
    %make
install    : |
    %make_install
    install -Dm 00644 data/aa-lsm-hook.conf $installdir/usr/share/defaults/etc/aa-lsm-hook.conf
    rm $installdir/etc/aa-lsm-hook.conf
    # Pre-enable service for Solus users
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../aa-lsm-hook.service $installdir/usr/lib/systemd/system/sysinit.target.wants/aa-lsm-hook.service
