name       : aa-lsm-hook
version    : 0.1.3
release    : 12
source     :
    - https://github.com/getsolus/aa-lsm-hook/archive/0.1.3.tar.gz : d3fa90fc87e0a32c29bec3767b5fa0cae48cdc932b691b4236d208a96e54fe23
license    : Apache-2.0
component  : system.base
summary    : AppArmor system integration
description: |
    AppArmor system integration
builddeps  :
    - golang
networking : yes
build      : |
    %make
install    : |
    %make_install
    # Pre-enable service for Solus users
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../aa-lsm-hook.service $installdir/usr/lib/systemd/system/sysinit.target.wants/aa-lsm-hook.service
