name       : aa-lsm-hook
version    : 0.0.3
release    : 9
source     :
    - https://github.com/getsolus/aa-lsm-hook/releases/download/v0.0.3/aa-lsm-hook-0.0.3.tar.xz : edc3a7d0d193a5db07c86832c9fc5dba26817cf26ac3c0736cea6af8e256e11e
license    : GPL-2.0-only
component  : system.base
summary    : AppArmor system integration
description: |
    AppArmor system integration
builddeps  :
    - musl-devel
optimize   :
    - size
    - lto
setup      : |
    # We want tiny musl binary to make it load faster
    %meson_configure -Dwith-static-binary=true
build      : |
    LD_PRELOAD='' %meson_build
install    : |
    LD_PRELOAD='' %meson_install
    # Pre-enable service for Solus users
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../aa-lsm-hook.service $installdir/usr/lib/systemd/system/sysinit.target.wants/aa-lsm-hook.service
