name       : aa-lsm-hook
version    : 0.1.4
release    : 14
source     :
    - git|https://github.com/getsolus/aa-lsm-hook.git : 125ff4b24369946f4cfb097252b6dae253453693
license    : Apache-2.0
component  : system.base
summary    : AppArmor system integration
description: |
    AppArmor system integration
builddeps  :
    - golang
networking : yes
build      : |
    %make
install    : |
    %make_install
    # Pre-enable service for Solus users
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../aa-lsm-hook.service $installdir/usr/lib/systemd/system/sysinit.target.wants/aa-lsm-hook.service
