name       : aa-lsm-hook
version    : 0.1.4
release    : 13
source     :
    - https://github.com/getsolus/aa-lsm-hook/archive/0.1.4.tar.gz : c8229d69a8594469fc59b2f4a7ce88888b8fcad6cb30a89b4043b3c013760289
license    : Apache-2.0
component  : system.base
summary    : AppArmor system integration
description: |
    AppArmor system integration
builddeps  :
    - golang
networking : yes
build      : |
    %make
install    : |
    %make_install
    # Pre-enable service for Solus users
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/sysinit.target.wants
    ln -sv ../aa-lsm-hook.service $installdir/usr/lib/systemd/system/sysinit.target.wants/aa-lsm-hook.service
